name: Keep Services Alive

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping-services:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping services
        run: |
          echo "Pinging services at $(date)"
          
          # Ping Supabase
          echo "Pinging Supabase..."
          SUPABASE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            https://cvukpuwtruisisnshfur.supabase.co/rest/v1/health)
          echo "Supabase response: $SUPABASE_STATUS"
          
          # Ping Render
          echo "Pinging Render service..."
          RENDER_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            https://accountant2.onrender.com/)
          echo "Render response: $RENDER_STATUS"
          
          # Log results
          echo "Ping completed at $(date)"
          
          # Optional: Fail the workflow if services are down
          if [ "$SUPABASE_STATUS" != "200" ] && [ "$RENDER_STATUS" != "200" ]; then
            echo "Warning: Both services returned non-200 status"
            # Uncomment below to make workflow fail when services are down
            # exit 1
          fi
